//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.09 at 06:00:58 PM MSK 
//


package ru.gkcdu.mailstatus.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DestinationAddress" type="{http://russianpost.org/operationhistory/data}Address" minOccurs="0"/&gt;
 *         &lt;element name="OperationAddress" type="{http://russianpost.org/operationhistory/data}Address"/&gt;
 *         &lt;element name="MailDirect" type="{http://russianpost.org/operationhistory/data}Country" minOccurs="0"/&gt;
 *         &lt;element name="CountryFrom" type="{http://russianpost.org/operationhistory/data}Country" minOccurs="0"/&gt;
 *         &lt;element name="CountryOper" type="{http://russianpost.org/operationhistory/data}Country"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressParameters", propOrder = {
    "destinationAddress",
    "operationAddress",
    "mailDirect",
    "countryFrom",
    "countryOper"
})
public class AddressParameters {

    @XmlElement(name = "DestinationAddress")
    protected Address destinationAddress;
    @XmlElement(name = "OperationAddress", required = true)
    protected Address operationAddress;
    @XmlElement(name = "MailDirect")
    protected Country mailDirect;
    @XmlElement(name = "CountryFrom")
    protected Country countryFrom;
    @XmlElement(name = "CountryOper", required = true)
    protected Country countryOper;

    /**
     * Gets the value of the destinationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getDestinationAddress() {
        return destinationAddress;
    }

    /**
     * Sets the value of the destinationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setDestinationAddress(Address value) {
        this.destinationAddress = value;
    }

    /**
     * Gets the value of the operationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getOperationAddress() {
        return operationAddress;
    }

    /**
     * Sets the value of the operationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setOperationAddress(Address value) {
        this.operationAddress = value;
    }

    /**
     * Gets the value of the mailDirect property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getMailDirect() {
        return mailDirect;
    }

    /**
     * Sets the value of the mailDirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setMailDirect(Country value) {
        this.mailDirect = value;
    }

    /**
     * Gets the value of the countryFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountryFrom() {
        return countryFrom;
    }

    /**
     * Sets the value of the countryFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountryFrom(Country value) {
        this.countryFrom = value;
    }

    /**
     * Gets the value of the countryOper property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountryOper() {
        return countryOper;
    }

    /**
     * Sets the value of the countryOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountryOper(Country value) {
        this.countryOper = value;
    }

}
