//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.09 at 06:00:58 PM MSK 
//


package ru.gkcdu.mailstatus.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OperationParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperType" type="{http://russianpost.org/operationhistory/data}Rtm02Parameter"/&gt;
 *         &lt;element name="OperAttr" type="{http://russianpost.org/operationhistory/data}Rtm02Parameter"/&gt;
 *         &lt;element name="OperDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationParameters", propOrder = {
    "operType",
    "operAttr",
    "operDate"
})
public class OperationParameters {

    @XmlElement(name = "OperType", required = true)
    protected Rtm02Parameter operType;
    @XmlElement(name = "OperAttr", required = true)
    protected Rtm02Parameter operAttr;
    @XmlElement(name = "OperDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operDate;

    /**
     * Gets the value of the operType property.
     * 
     * @return
     *     possible object is
     *     {@link Rtm02Parameter }
     *     
     */
    public Rtm02Parameter getOperType() {
        return operType;
    }

    /**
     * Sets the value of the operType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rtm02Parameter }
     *     
     */
    public void setOperType(Rtm02Parameter value) {
        this.operType = value;
    }

    /**
     * Gets the value of the operAttr property.
     * 
     * @return
     *     possible object is
     *     {@link Rtm02Parameter }
     *     
     */
    public Rtm02Parameter getOperAttr() {
        return operAttr;
    }

    /**
     * Sets the value of the operAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rtm02Parameter }
     *     
     */
    public void setOperAttr(Rtm02Parameter value) {
        this.operAttr = value;
    }

    /**
     * Gets the value of the operDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperDate() {
        return operDate;
    }

    /**
     * Sets the value of the operDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperDate(XMLGregorianCalendar value) {
        this.operDate = value;
    }

}
