//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.09 at 06:00:58 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://russianpost.org/operationhistory/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gkcdu.mailstatus.bindings;
