//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.09 at 06:00:58 PM MSK 
//


package ru.gkcdu.mailstatus.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SendCtg" type="{http://russianpost.org/operationhistory/data}Rtm02Parameter" minOccurs="0"/&gt;
 *         &lt;element name="Sndr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Rcpn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserParameters", propOrder = {
    "sendCtg",
    "sndr",
    "rcpn"
})
public class UserParameters {

    @XmlElement(name = "SendCtg")
    protected Rtm02Parameter sendCtg;
    @XmlElement(name = "Sndr")
    protected String sndr;
    @XmlElement(name = "Rcpn")
    protected String rcpn;

    /**
     * Gets the value of the sendCtg property.
     * 
     * @return
     *     possible object is
     *     {@link Rtm02Parameter }
     *     
     */
    public Rtm02Parameter getSendCtg() {
        return sendCtg;
    }

    /**
     * Sets the value of the sendCtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rtm02Parameter }
     *     
     */
    public void setSendCtg(Rtm02Parameter value) {
        this.sendCtg = value;
    }

    /**
     * Gets the value of the sndr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndr() {
        return sndr;
    }

    /**
     * Sets the value of the sndr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndr(String value) {
        this.sndr = value;
    }

    /**
     * Gets the value of the rcpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcpn() {
        return rcpn;
    }

    /**
     * Sets the value of the rcpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcpn(String value) {
        this.rcpn = value;
    }

}
